config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get '/homes/about' => 'homes#about', as: 'about'
  get '/homes/top' => 'homes#top', as: 'top'

  devise_for :users

  resources :books, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :users, :index] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

 
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end


  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum:50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

    def followings
      user = User.find(params[:id])
      @users = user.followings
    end

    def followers
      user = User.find(params[:id])
      @users = user.followers
    end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, )
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<h2>Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(75, 75) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <% if user == current_user %>
          <td></td>
        <% else %>
          <% if user.is_followed_by?(current_user) %>
            <td><%= link_to 'フォロー外す', user_relationships_path(user), method: :delete %></td>
          <% else %>
            <td><%= link_to 'フォローする', user_relationships_path(user), method: :post %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/users/_info.html.erb
<div class="container">
  <h2>User info</h2>

  <%= image_tag user.get_profile_image(100, 100) %>

  <table class="table">
    <tbody>
      <tr>
        <td><strong>name</strong></td>
        <td><strong><%= user.name %></strong></td>
      </tr>
      <tr>
        <td><strong>introduction</strong></td>
        <td><strong><%= user.introduction %></strong></td>
      </tr>
      <tr>
        <td><strong>follows</strong></td>
        <td><strong>
          <%= link_to followings_user_path(user) do %>
            <%= user.followings.count %>
          <% end %>
        </strong></td>
      </tr>
      <tr>
        <td><strong>followers</strong></td>
        <td><strong>
          <%= link_to followers_user_path(user) do %>
            <%= user.followers.count %>
          <% end %>
        </strong></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <% if user == current_user %>
      <%= link_to edit_user_path(@user), class:'col d-grit gap-2 btn btn-outline-secondary my-3' do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    <% else %>
      <% if user.is_followed_by?(current_user) %>
        <%= link_to 'フォロー解除', user_relationships_path(user), method: :delete, class:'btn btn-danger' %>
      <% else %>
        <%= link_to 'フォローする', user_relationships_path(user), method: :post, class:'btn btn-success' %>
      <% end %>
    <% end %>
    <% if user != current_user && current_user.is_followed_by?(user) && user.is_followed_by?(current_user) %>
        <%= link_to 'Chat', chat_path(user.id), class:'btn btn-outline-secondary ml-3'%>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col-xl-6 col-lg-8 col-md-10 col-11 mx-auto p-0">
      <div class="row">
        <h2>User info</h2>
      </div>

      <div class="row">
        <%= render 'layouts/errors', obj:@user %>
      </div>
          
      <div class="row">
        <div class="col-11">
          <%= form_with model:@user do |f| %>

            <div class="row">
              <div class="form-group col-12">
                <label for="inputName">Name</label>
                <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col">
                <label for="inputImage">Image</label>
                <%= f.file_field :profile_image, pleceholder: "プロフィール画像", accept: "image/*", class: "form-control-file" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col">
                <label for="inputIntroduction">Introduction</label>
                <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介", class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col">
                <%= f.submit 'Update User', class:'d-grit gap-2 btn btn-secondary mt-1' %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.present? %>
  <table class="table">
    <thead>
      <tr>
        <td>image</td>
        <td>name</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(75, 75) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/followings.html.erb
<h2>Following Users</h2>
<% if @users.present? %>
  <table class="table">
    <thead>
      <tr>
        <td>image</td>
        <td>name</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(75, 75) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= render 'info', user:@user %>



      <div class="row">
        <div class="col">
          <h2>New book</h2>
          <%= form_with model:@new_book, url:books_path, method: :post do |f| %>
            <div class="row">
              <div class="form-group col-12">
                <label for="inputName">Title</label>
                <%= f.text_field :title, class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-12">
                <label for="inputName">Opinion</label>
                <%= f.text_area :opinion, class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-12">
                <%= f.submit 'Create Book', class:'d-grit gap-2 btn btn-success mt-2' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= render 'index', users:@users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      
      <%= render 'info', user:@user %>


      <div class="row">
        <div class="col">
          <h2>New book</h2>
          <%= form_with model:@new_book, url:books_path, method: :post do |f| %>
            <div class="row">
              <div class="form-group col-12">
                <label for="inputName">Title</label>
                <%= f.text_field :title, class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-12">
                <label for="inputName">Opinion</label>
                <%= f.text_area :opinion, class: "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-12">
                <%= f.submit 'Create Book', class:'d-grit gap-2 btn btn-success mt-2' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag @user.get_profile_image(75, 75) %>
                <% end %>
              </td>
              <td><%= link_to book.title, "/books/#{book.id}" %></td>
              <td><%= book.opinion %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>