config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get '/homes/about' => 'homes#about', as: 'about'
  get '/homes/top' => 'homes#top', as: 'top'

  devise_for :users

  resources :books, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :users, :index] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<h3><%= obj.errors.count %> errors prohibited this obj from being saved.</h3>
<ul class="pl-4">
  <% obj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cf1df73f36.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
          <%= link_to 'Bookers', '/', class:'navbar-brand text-white' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-house"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-white' do%>
                    <i class="fa-solid fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do%>
                    <i class="fa-solid fa-right-from-bracket"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to '/', class: 'nav-link text-white' do %>
                    <i class="fa-solid fa-house"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-right-to-bracket"></i>
                  Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row pt-1">
          <div class="col-md-8 offset-md-4">
            <%= render 'searches/search' %>
          </div>
        </div>
      </div>

    </header>

    <main>
      <%= notice %>
      <%= yield %>
    </main>

    <footer class="w-75 mx-auto mt-5">
      <p class="text-center">CopyRight Infratop.inc</p>
    </footer>

  </body>
</html>